name: Versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checking-versions:
    runs-on: ubuntu-latest

    steps:
      - name: printing_commands
        run: |
          echo "Printing Commands"
          pwd
          ls -lrt
          git --version
  installing-packages:
    runs-on: ubuntu-latest
      
    steps:
      - name: Updating and installing softwares
        run: |
          sudo apt-get update -y
          java --version || true
          sudo apt install default-jdk -y
          java --version
